name: ZillitPO
options:
  bundleIdPrefix: com.zillit.coda
  deploymentTarget:
    iOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  ZillitPO:
    type: application
    platform: iOS
    sources:
      - ZillitPO
    settings:
      base:
        INFOPLIST_FILE: ZillitPO/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.zillit.coda.po
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "13.0"
